//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HurmatullinSystemForInstitute.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int id { get; set; }
        public string kafedra_code { get; set; }
        public string fio { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> chef { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Kafedra Kafedra { get; set; }
        public virtual Role Role { get; set; }
    }
}
